version: '3.8'

services:
  # PHP + Laravel (có supervisor chạy queue bên trong)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    expose:
      - "9000"  # cho nginx truy cập
    depends_on:
      - db
      - redis
    networks:
      - laravel_net

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

  # Redis (dùng cho queue/cache)
  redis:
    image: redis:alpine
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_net

  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  # PhpMyAdmin (tùy chọn)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel_net

volumes:
  dbdata:

networks:
  laravel_net:
